title: Balthasarium | echtland&reg; Co-Working
email: kaeseguerilla@gmail.com
description: >
  Die Top Coworking Location in Pfaffenhofen für Gründer, Startups und
  Freelancer by echtland&reg; Co-Working
keywords: >
  pfaffenhofen, coworking, space, bürogemeinschaft, balthasarium, echtland,
  arbeitsplatz, besprechung, raum, mieten

baseurl: ""
assets_base_url: "assets/"

markdown: kramdown
source: src
destination: dist

repository: Echtland/echtland-coworking

exclude:
  - .babelrc
  - .nvmrc
  - .ruby-version
  - bin
  - Gemfile
  - Gemfile.lock
  - node_modules
  - npm-debug.log
  - package.json
  - Procfile.development
  - webpack.config.js
  - yarn.lock
